### ISSUE TITLE
Dereference symlinks on state restore

### ISSUE THREAD

**Issue by x42** [lv2/lilv#13] opened 2018-10-26 20:01 UTC
`lilv_state_restore`'s retrieve callback should dereference symlinks by calling readlink.

- load a file into a plugin. e.g. /file.test
- save state. lilv generates two symlinks:
  *  `state-dir/file.test` -> `externals/file.test`
  *  `externals/file.test` -> `/file.test`
- re-load plugin, restore state.  the plugin uses  `state-dir/file.test`

Now copy the plugin or save a preset. the file `state-dir/file.test` is used as new original.  This causes various issues.

Also simply inspecting which file the plugin uses only points to  `state-dir/file.test`. From a user's POV it would be nice if the plugin would show the canonical path.

**Comment by sadko4u** [comment] 2020-01-08 00:52
Bump! I've just met the same problem.

**Comment by sadko4u** [comment] 2020-06-24 21:11
The related issue:
https://github.com/sadko4u/lsp-plugins/issues/119

It think that using symlinks is completely wrong way.
Instead of such magic a dedicated mapping file can be used.
The benefits: before saving the preset, the file is recreated. Once new mapping is defined, the new record is just added to this mapping file. There is no need to monitor symlinks and manage them.

ilv spoils the file name and replaces it with symlink name on the first state load.
Consider there are two files in different folders 'AgogoHigh-0.wav'. The first one will be replaced as 'AgogoHigh-0.wav' but the second with 'AgogoHigh-0.wav.2'.
That's bad practice since some plugins may expect to receive original file name. Ater state load, the user will see some strange 'AgogoHigh-0.wav.2' in the interface which was never used before:

![image](https://user-images.githubusercontent.com/12834464/85627857-de96a700-b677-11ea-8d95-437baeef110f.png)

**Comment by x42** [comment] 2020-06-24 22:02
my 2c: I'd very much prefer to use OS provided features for instead of inventing a custom mapping file, particularly since https://github.com/lv2/lilv/commit/81babb758e614ae622b39849c0c65cf38505a912

**Comment by sadko4u** [comment] 2020-06-24 22:25
> my 2c: I'd very much prefer to use OS provided features for instead of inventing a custom mapping file

Several file systems like VFAT don't support symlinks. So if you store the project/preset on such file system, it will be completely malformed.
There is no difference between set of symlinks and one mapping file since both provide <key => value> mapping. But file solution is much better portable. And, moreover, you even don't need to control the removal of symlinks, just overwrite the file with new mapping data when required.

Hardlinks are not portable between volumes, you can not use them to guarantee the consistency of LV2 State/Preset file.

**Comment by x42** [comment] 2020-06-25 05:17
> So if you store the project/preset on such file system, it will be completely malformed.

Try it :) lilv falls back to copy the file if links are not available.

**Comment by sadko4u** [comment] 2020-06-25 13:48
> Try it :) lilv falls back to copy the file if links are not available.

Moreover, it is inappriate solution. You get:
1. File copied instead of symlink'ed. Changing original file won't take an effect.
2. The copy of file will take extra space.
3. The file will be renamed if it's name collides with another file name.

**Comment by sadko4u** [comment] 2020-06-25 14:06
Yet another case of corrupting session data in Ardour:
https://github.com/sadko4u/lsp-plugins/issues/120

1. Create new session, create bus, put multisampler_x12.
2. Open the UI, load some file, close UI.
3. Perform Session -> rename.
4. You will already get inconsistent session, without need to close it.

**Comment by drobilla** [comment] 2020-06-28 10:42
Yes, symlinks are awesome for all kinds of reasons.

That said, this is clearly a problem.  This is still open because I haven't had time to properly look into it, and I don't think effectively mutating state on load time is something to be done blindly/lightly.  That seems like it'd have even more unintended consequences.  Is such a state "equal"?  What if the user themselves picked a symlink (because that's how their content is organized or whatever)?  Is it really okay to completely eradicate any and all symlinking (which is what `realpath` would do)?  Should states where the user actually selected different paths but they happen to be the same one be equal?  Are there problems with states that aren't superficially equal (in that they have the same paths) being equal on loading?  And so on, and so on.

Then there's the Windows situation.  The obvious way to avoid all of this is to just use absolute paths everywhere, but then state can't be realistically archived/moved at all, which sucks quite a bit.  An option in the API would be good for this, though, but that's an API change.

... etc etc.  I'll try to find time to look into this, particularly since API changes are on the horizon anyway, but I think I need to actually write a half decent test suite and such because this is another thing that doesn't seem like it will end well at all by patching over scenarios in combinations of very complicated hosts and plugins that all do their own things and/or want some particular behaviour in some particular case.  This is a very complex problem space with a lot of trade-offs.

I don't see what a "mapping file" would do though.  If there's no links... mapping to/from what?

**Comment by sadko4u** [comment] 2020-07-07 22:35
> Should states where the user actually selected different paths but they happen to be the same one be equal

I think mapping many (virtual) to one (real) paths is possible without any problems. This will save the space if we will make the session 'portable'. Under portable session I mean the session where the files referenced by the state are copied into the project tree that contains such state.

> Is it really okay to completely eradicate any and all symlinking (which is what realpath would do)

I think it is a good solution. The benefits:
* you just read one file;
* the directory does not blow up with symlinks. Many directory entries (which symlinks actually are) -> less performance while accessing to the directory entries;
* you can manually edit the file by search&replace;
* the solution is portable between any file system since any file system supports text files;
* file contents is just replaced on save, no need to manage individual symlinks.

> Should states where the user actually selected different paths but they happen to be the same one be equal

No, I think different paths to files should be always considered as different paths. If user does some magic on symlinks/hardlinks, then we should keep that's all on his own.

> Are there problems with states that aren't superficially equal (in that they have different file paths) being equal on loading?

I think no.

> I don't see what a "mapping file" would do though. If there's no links... mapping to/from what?

Here can be a simple example:
```
lv2fs://AgogoLow.wav=/path/to/samples/AgogoLow.wav
lv2fs://AgogoHigh.wav=/path/to/samples/AgogoHigh.wav
# etc
```

When the host archives the state, it just replaces absolute paths with paths to the copies stored inside the session, so we get:
```
lv2fs://AgogoLow.wav=external_data/AgogoLow.wav
lv2fs://AgogoHigh.wav=external_data/AgogoHigh.wav
# etc
```

**Comment by drobilla** [comment] 2020-07-08 19:29
Your responses to the "is it okay to eradicate any and all symlinking" and "should states ... be equal?" contradict one another.

If you want to preserve exactly what the user selected, even if it's a symlink, you can't just ram everything through `realpath`.

> When the host archives the state

The entire point of this design is that anything can trivially archive the state.  Maybe the trade-offs aren't perfect and some of the symlink issues need to be sorted out, but having weird opaque state that needs to be specially handled by the host or LV2 specific tools is a really big burden.  It was avoided very much on purpose.

In any case, I still don't see the point of a mapping file.  If that's the situation, then just store the absolute paths in the state directly.  What benefit does referring to some strange URI in the state, then having to look up in some other file what file that actually refers to bring?

**Comment by sadko4u** [comment] 2020-07-08 19:46
> Your responses to the "is it okay to eradicate any and all symlinking" and "should states ... be equal?" contradict one another.

No, they don't. Consider we have a mapping file:
```
lv2fs://AgogoLow.wav=/path/to/samples/AgogoLow.wav
lv2fs://AgogoHigh.wav=/path/to/samples/AgogoHigh.wav
```

The plugin knows that lv2fs://AgogoLow.wav refers to some file and lv2fs://AgogoHigh.wav refers to some another file. And it always can obtain their real paths - /path/to/samples/AgogoLow.wav and /path/to/samples/AgogoHigh.wav

**BUT** the host and the plugin don't even need to take attention of what /path/to/samples/AgogoLow.wav and /path/to/samples/AgogoHigh.wav are. Are these both symlinks or hardlinks, or some other stuff - that doesn't matter. The user is responsible for that these files contain the required data for the plugin.

> The entire point of this design is that anything can trivially archive the state

There is a problem of reading key-value file? Even grep/awk can do this.

> If that's the situation, then just store the absolute paths in the state directly. 

And forget about the portability of the session I suppose?

> What benefit does referring to some strange URI in the state, then having to look up in some other file what file that actually refers to bring?

The main benefits are keeping the same behaviour for any operating system and keeping possibility to replace real paths by others from the host side just by editing one file. All other benefits I've provided in the previous post.

**Comment by drobilla** [comment] 2020-07-09 07:47
> The main benefits are keeping the same behaviour for any operating system and keeping possibility to replace real paths by others from the host side just by editing one file. All other benefits I've provided in the previous post.

I don't see how these are benefits compared to just storing the actual paths in the state, all of these things are true then too.  Effectively this _is_ storing the actual paths in the state, just with a bunch of extra complexity.

Can you describe something that would be possible with this, that isn't possible with simply storing the actual paths in the state?

**Comment by sadko4u** [comment] 2020-07-09 09:05
> Can you describe something that would be possible with this, that isn't possible with simply storing the actual paths in the state?

I think that by mapping files the plugin delegates to the host the possibility to move the file from one location to another.
From another side, if plugin does not map the file name, it strictly prohibits to change it.
For example, LSP Plugins may map files which are stored internally inside the bundle and do not exist on the file system. The only difference between real paths and builtin paths is that last start with the **builtin://** prefix. Changing such paths may break the state of the plugin.

**Comment by drd-ableton** [comment] 2020-07-09 10:08
Right, I forgot about paths that don't show up transparently in the state, thanks.

I'm still extremely skeptical of losing all the advantages of the current approach, but that needs to work somehow anyway.

**Comment by drobilla** [comment] 2020-07-09 10:09
Right, I forgot about paths that don't show up transparently in the state, thanks.

I'm still extremely skeptical of losing all the advantages of the current approach, but that needs to work somehow anyway.

**Comment by alex-tee** [comment] 2020-07-14 10:26
i'd vote for the mapping file as well. I think it's a cleaner approach to let the host manage paths however it wants and plugins would only save some kind of URI or ID given by the host (I'd just use an integer and add 1 for each new file) (or even the file hash!) that the host knows how to translate to the actual file. I mentioned the use of a file pool on IRC before, this is a similar concept.

the plugin should ideally only store a URI/ID/hash that translates to the actual file. the mapping file would keep a path to the actual file and the URI/ID/hash

also I'm not sure if this is already done with the current approach, but there should be a mechanism to prevent access to the same file by different plugins. eg. the host would copy the file to a temporary dir and let the plugin use the copy instead of the original.

**Comment by drobilla** [comment] 2020-07-14 16:52
Lilv's state interface intentionally does not "let the host manage paths however it wants".  It implements the clean/simple/portable approach that makes normal preset-like bundles, and uses symlinks for the path stuff for the above-mentioned benefits like being transparent to / archivable by every generic tool there is.  The only way some extra mapping file thing is a good idea is if it's literally impossible to make things work otherwise.  I'm not convinced that's the case, and I think y'all are much too keen to throw the baby out with the bathwater here.

That said, you are free to implement state however you want, though I definitely don't recommend doing so without very good concrete reasons.

**Comment by paulfd** [comment] 2020-07-27 10:58
One behavior could be to dereference the symlink twice in `lilv_absolute_path()`, for the following logic: if the saved state file is a symlink AND the symlink targets a file in `state->link_dir`, then dereference the symlink twice and preset the resulting path to the user. `state->link_dir` does not seem populated (I'm using Ardour master as the host atm), that might be the main blocking point for now. I can try to propose something if you feel like it's a proper solution.

**Comment by drobilla** [comment] 2020-07-28 18:54
It's probably very tedious and platform-specific to be so precise about symlinks, but it might be possible.  I am not sure what the advantage would be compared to just always doing it though?

(At a high level, this is stalled because I'm not really confident to touch it _at all_.  Only one non-trivial change to the state stuff has been merged in the past few years, and it seemed reasonable, so I did it... and it broke things.  I'm extremely wary of "does what I want for my plugin/host" sort of proposals to the libraries, with good reason.  Tests first.)

**Comment by paulfd** [comment] 2020-07-28 21:04
> It's probably very tedious and platform-specific to be so precise about symlinks, but it might be possible. I am not sure what the advantage would be compared to just always doing it though?

You mean at the plugin level for example? I cannot be sure how the state is arranged within the state directory. One symlink, two symlinks, a file, ... Technically I guess there is a lot of freedom there? If someone uses some other mean that what lilv does now I mean.

> (At a high level, this is stalled because I'm not really confident to touch it _at all_. Only one non-trivial change to the state stuff has been merged in the past few years, and it seemed reasonable, so I did it... and it broke things. I'm extremely wary of "does what I want for my plugin/host" sort of proposals to the libraries, with good reason. Tests first.)

I can understand this, no problem at all :slightly_smiling_face:  I am mostly then putting in a chip in there to argue that the user experience of finding oneself within a "saved state directory" is confusing. If we converge to a satisfactory solution I can try to help implement and test it out.

**Comment by drobilla** [comment] 2020-07-28 21:59
> You mean at the plugin level for example? I cannot be sure how the state is arranged within the state directory. One symlink, two symlinks, a file, ... Technically I guess there is a lot of freedom there? If someone uses some other mean that what lilv does now I mean.

I just mean at the C code level in general.  Full dereferencing (i.e. `realpath` or `GetFullPathName`) is a thing you can do mostly anywhere, but I'm not sure about how portable the ability to choose how many "steps" you want to partially-dereference a symlink are.

i.e. there is no "twice" normally.  It just resolves all the way to the not-symlink file if you resolve it at all.

**Comment by paulfd** [comment] 2020-07-28 22:58
The "twice" is nice because lilv knows that it stores the state with this structure. I could go through all the symlinks to the real path at the plugin level, but you will have corner cases if the file loaded was a symlink in the first place. The output file would not be the file the user loaded, which is again not a great UX (albeit a better one for most users).

**Comment by drobilla** [comment] 2020-07-29 06:53
It doesn't really know any of that at load time, it just reads files from wherever.  That information would have be stored somehow, e.g. like @sadko4u was saying.  Probably the most consistent LV2ey way to do this would be to put information in a manifest.  That could be done in the state bundle, or even in the link directories themselves.

**Comment by drobilla** [comment] 2020-11-30 21:56
> Now copy the plugin or save a preset. the file state-dir/file.test is used as new original. This causes various issues.

Such as?

**Comment by drobilla** [comment] 2020-12-01 11:25
I'm not able to reproduce an issue here with current Ardour and LSP Multi-Sampler masters.  If I save a preset that uses some external file, the state on disk links to the external file as expected.  Changing the preset again does the same.  If I load the plugin in an Ardour session and save, the state in the session links to `externals` as expected.  If I close Ardour and re-load the session, this is loaded, and everything looks the same in the plugin UI.

Please provide precise reproduction instructions or close this issue.

**Comment by drobilla** [comment] 2020-12-18 17:24
Closing as I can not find a problem here, and the original ticket is a description of a proposed solution, not an issue.

**Closed by drobilla** 2020-12-18 17:24 UTC
